### ISSUE TITLE
Client ID not provided when calling API endpoints

### ISSUE THREAD

**Issue by playitcool** [justintv/twitch-js-sdk#23]
https://github.com/justintv/twitch-js-sdk/blob/master/twitch.js#L38-L42

This should either include the client id in the header of the ajax call (per this [blog post](https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.7kini0ja5)) or append it in params.

I tried adding the client id in the headers of the ajax call - that did not work. What _did_ work was to append it to params.

`params.client_id = Twitch._config.clientId;`

**Comment by Fasani** [comment]
Did you get it working playitcool, this recently broke... :-(

**Comment by Fasani** [comment]
I hacked it quick pn line 37 of Twitch.js

It seems they changed the API so that the client_id is needed with some calls now previous it was not needed.

    $.ajax({
      url: url + '?client_id=' + Twitch._config.clientId + '&' + $.param(params),
      dataType: 'jsonp',
      timeout : REQUEST_TIMEOUT
    })

I now this is messy but, hey it works for now, for me... :-)

**Comment by Fasani** [comment]
Here some one made a better PR

https://github.com/justintv/twitch-js-sdk/pull/21

See what they did, this fixes it.

**Comment by playitcool** [comment]
Hey fasani, thanks for the update. And yes way better PR 💯
