### ISSUE TITLE
Stream to Twitch from web

### ISSUE THREAD

**Issue by dsernst** [justintv/twitch-js-sdk#6]
Does this sdk support streaming web-based games to Twitch?

**Comment by sutt0n** [comment]
I don't believe so - if you read the main `README.md`, you'll see that it's basically a JavaScript SDK (although the repository says `SDK` and the code says `Twitch.api` - not sure what went on there) that allows you to interact with Twitch's Developer API.

If you want to stream web-based games, then you can just stream your browser window.

**Comment by dsernst** [comment]
Yeah, I hear you. I have a web game, and I was hoping to let my users stream to Twitch with only a click or two, without needing to install anything.
